apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/nvinto-ocm-tenant/partner-catalog/partner-catalog@sha256:6556ce9ec8afd04c1eb85e2777f53ca9bac60db77f55ccfa11440c2042f28615
        name: my-java-springboot
        resources: {}
status: {}
